language: C
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- sudo apt-get install libssl-dev uml-utilities

script:
- 'git clone https://github.com/bambusoft/ntvl.git'
- 'dir'
- 'cd ntvl'
- 'make'
- 'tar -czvf ntvl.tar.gz *'
- 'curl -T ntvl.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/NTVL/ubuntu2/'
